INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 1", "Category 1", 1000, "Today", "Tomorrow");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 2", "Category 2", 1000, "Today", "Tomorrow");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 3", "Category 1", 1000, "Today", "Tomorrow");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 4", "Category 2", 1000, "Today", "Tomorrow");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 5", "Category 1", 1000, "Today", "Tomorrow");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 6", "Category 2", 1000, "Today", "Tomorrow");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 7", "Category 1", 1000, "Today", "Tomorrow");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 8", "Category 2", 1000, "Today", "Tomorrow");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 9", "Category 1", 1000, "Today", "Tomorrow");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 10", "Category 2", 1000, "Today", "Tomorrow");
INSERT INTO users (name, age) VALUES ("Cynthia", 19);
INSERT INTO users (name, age) VALUES ("Dianne", 18);
INSERT INTO users (name, age) VALUES ("Lana", 18);
INSERT INTO users (name, age) VALUES ("Serena", 18);
INSERT INTO users (name, age) VALUES ("Tiffany", 18);
INSERT INTO users (name, age) VALUES ("Ashlynn", 19);
INSERT INTO users (name, age) VALUES ("Alice", 18);
INSERT INTO users (name, age) VALUES ("Luna", 18);
INSERT INTO users (name, age) VALUES ("Katrina", 18);
INSERT INTO users (name, age) VALUES ("Catherine", 19);
INSERT INTO users (name, age) VALUES ("Katherine", 18);
INSERT INTO users (name, age) VALUES ("Cathyrine", 18);
INSERT INTO users (name, age) VALUES ("Kathyrine", 18);
INSERT INTO users (name, age) VALUES ("Kaitlyn", 19);
INSERT INTO users (name, age) VALUES ("Caitlyn", 18);
INSERT INTO users (name, age) VALUES ("Caitlin", 18);
INSERT INTO users (name, age) VALUES ("Kaitlin", 18);
INSERT INTO users (name, age) VALUES ("Catelyn", 18);
INSERT INTO users (name, age) VALUES ("Katelyn", 19);
INSERT INTO users (name, age) VALUES ("Katalin", 18);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 2, 2);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 3, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 4, 4);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 5, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 6, 6);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 7, 7);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 8, 8);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 9, 9);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 10, 10);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 11, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 12, 2);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 13, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 14, 4);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 15, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 16, 6);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 17, 7);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 18, 8);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 19, 9);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 20, 10);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 2, 2);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 3, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 4, 4);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 5, 5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 6, 6);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 7, 7);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 8, 8);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 9, 9);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 10, 10);
